app/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('account/', include('django.contrib.auth.urls')),
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('post/<id>/', views.comment, name='comment'),
    path('profile/<username>/', views.profile, name='profile'),
    path('user_profile/<username>/', views.user_profile, name='user_profile'),
    path('search/', views.search_profile, name='search'),
    path('like/<id>', views.like, name='like'),
    path('unfollow/<id>', views.unfollow, name='unfollow'),
    path('follow/<id>', views.follow, name='follow')
]

instagram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView, LogoutView
from . import views as main
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('registration.backends.simple.urls')),
    # # path('index/',main.index,name='index'),
   
    path('login/',LoginView.as_view(template_name='registration/login.html'),name='login'),
    path('logout/',LogoutView.as_view(template_name='login.html'),name='logout')
    
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User

# profile model
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile',null=True)
    profile_picture = models.ImageField(upload_to='images/')
    bio = models.TextField(max_length=500, default="My Bio", blank=True)
    name = models.CharField(blank=True, max_length=120)
    location = models.CharField(max_length=60, blank=True)

    # string rep of class instance to get exact username on search
    # def __str__(self):
    #         return f'{self.user.username} Profile'

    def __str__(self):
        return self.user
    
    def save_profile(self):
        self.user

    def delete_profile(self):
        self.delete()

    @classmethod
    def search_profile(cls, name):
        return cls.objects.filter(user__username__icontains=name).all()

# class post
class Post(models.Model):
    image = models.ImageField(upload_to='posts/',null=True)
    name = models.CharField(max_length=250, blank=True)
    caption = models.CharField(max_length=250, blank=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts',null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)

    # def __str__(self):
    #         return f'{self.user.name} Post'

    def __str__(self):
        return self.name


    def save_image(self):
        self.save()

    def delete_image(self):
        self.delete()

    def total_likes(self):
        return self.likes.count()

    

   
# add class comment
class Comment(models.Model):
    comment = models.TextField(null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments',null=True)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='comments',null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.comment

    def save_comment(self):
        self.save()

    def delete_comment(self):
        self.delete()

    @classmethod
    def get_comments(cls, id):
        comments = Comment.objects.filter(post__pk=id).all()
        return comments

    

# class follow

class Follow(models.Model):
    follower = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='following',null=True)
    followed = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='followers',null=True)

    def __str__(self):
        return f'{self.follower} Follow'
           

            
    def save_follow(self):
        self.save()

    def delete_follow(self):
        self.delete()

app/templates/base.html
{% load static %}
<html lang="en">
<head>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-144351462-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-144351462-1');
    </script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {%block css%}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {%endblock%}
            
    
    <title>Insta-lite</title>
</head>
<body class="reg">
{% block content %}

{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

app/templates/home.html
{%load static%}
{% load fontawesome_5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% fontawesome_5_static %} 
    {%block styles%}
    <link rel="stylesheet" href="{%static 'css/home.css'%}" >
    {%endblock%}
</head>
<body>
    <nav class="navbar">
        <div class="nav-wrapper">
            <img src="{%static 'img/title.png'%}" class="brand-img" alt="">
            <form class="search-container">
                <input type="text" placeholder="Search.." name="search">
                <button type="submit"><i class="fa fa-search"></i></button>
              </form>
           
            <div class="nav-items">
                
                <a class="icon" href="/" role="link" tabindex="0">
                    <svg aria-label="Home" class="_ab6-" color="#262626" fill="#262626" height="24" role="img" viewBox="0 0 24 24" width="24"><path d="M9.005 16.545a2.997 2.997 0 012.997-2.997h0A2.997 2.997 0 0115 16.545V22h7V11.543L12 2 2 11.543V22h7.005z" fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="2"></path></svg>
                </a>

                <a aria-label="Direct messaging - 0 new notifications link" class="icon" href="/direct/inbox/" role="link" tabindex="0">
                    <svg aria-label="Messenger" class="_ab6-" color="#262626" fill="#262626" height="24" role="img" viewBox="0 0 24 24" width="24"><path d="M12.003 1.131a10.487 10.487 0 00-10.87 10.57 10.194 10.194 0 003.412 7.771l.054 1.78a1.67 1.67 0 002.342 1.476l1.935-.872a11.767 11.767 0 003.127.416 10.488 10.488 0 0010.87-10.57 10.487 10.487 0 00-10.87-10.57zm5.786 9.001l-2.566 3.983a1.577 1.577 0 01-2.278.42l-2.452-1.84a.63.63 0 00-.759.002l-2.556 2.049a.659.659 0 01-.96-.874L8.783 9.89a1.576 1.576 0 012.277-.42l2.453 1.84a.63.63 0 00.758-.003l2.556-2.05a.659.659 0 01.961.874z"></path></svg></a>
                <a href="" class="icon">
                    <svg aria-label="New post" class="_ab6-" color="#262626" fill="#262626" height="24" role="img" viewBox="0 0 24 24" width="24"><path d="M2 12v3.45c0 2.849.698 4.005 1.606 4.944.94.909 2.098 1.608 4.946 1.608h6.896c2.848 0 4.006-.7 4.946-1.608C21.302 19.455 22 18.3 22 15.45V8.552c0-2.849-.698-4.006-1.606-4.945C19.454 2.7 18.296 2 15.448 2H8.552c-2.848 0-4.006.699-4.946 1.607C2.698 4.547 2 5.703 2 8.552z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path><line fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" x1="6.545" x2="17.455" y1="12.001" y2="12.001"></line><line fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" x1="12.003" x2="12.003" y1="6.545" y2="17.455"></line></svg>
                </a>
                


                <a class="icon" href="/explore/" role="link" tabindex="0">
                    <svg aria-label="Find People" class="_ab6-" color="#262626" fill="#262626" height="24" role="img" viewBox="0 0 24 24" width="24"><polygon fill="none" points="13.941 13.953 7.581 16.424 10.06 10.056 16.42 7.585 13.941 13.953" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></polygon><polygon fill-rule="evenodd" points="10.06 10.056 13.949 13.945 7.581 16.424 10.06 10.056"></polygon><circle cx="12.001" cy="12.005" fill="none" r="10.5" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></circle></svg>
                </a>


                <a class="icon" href="/accounts/activity/"><svg aria-label="Activity Feed" class="_ab6-" color="#262626" fill="#262626" height="24" role="img" viewBox="0 0 24 24" width="24"><path d="M16.792 3.904A4.989 4.989 0 0121.5 9.122c0 3.072-2.652 4.959-5.197 7.222-2.512 2.243-3.865 3.469-4.303 3.752-.477-.309-2.143-1.823-4.303-3.752C5.141 14.072 2.5 12.167 2.5 9.122a4.989 4.989 0 014.708-5.218 4.21 4.21 0 013.675 1.941c.84 1.175.98 1.763 1.12 1.763s.278-.588 1.11-1.766a4.17 4.17 0 013.679-1.938m0-2a6.04 6.04 0 00-4.797 2.127 6.052 6.052 0 00-4.787-2.127A6.985 6.985 0 00.5 9.122c0 3.61 2.55 5.827 5.015 7.97.283.246.569.494.853.747l1.027.918a44.998 44.998 0 003.518 3.018 2 2 0 002.174 0 45.263 45.263 0 003.626-3.115l.922-.824c.293-.26.59-.519.885-.774 2.334-2.025 4.98-4.32 4.98-7.94a6.985 6.985 0 00-6.708-7.218z"></path></svg><div class="_acul"></div></a>

                
                <div class="icon user-profile"></div>
               
            </div>
        </div>
    </nav>
    <!-- section -->
    <section class="main">
        <div class="stories">

            <div class="left">
                <div class="story">
                    <div class="card">
                        <div class="profile-pic">
                            <img src="{%static 'img/back2.png'%}" alt=""></div>
                            <p class="username">Leo</p>
                    </div>
                     <div class="card">
                        <div class="profile-pic">
                            <img src="{%static 'img/back2.png'%}" alt=""></div>
                            <p class="username">Leo</p>
                    </div>
                    <div class="card">
                        <div class="profile-pic">
                            <img src="{%static 'img/back2.png'%}" alt=""></div>
                            <p class="username">Leo</p>
                    </div>
                    <div class="card">
                        <div class="profile-pic">
                            <img src="{%static 'img/back2.png'%}" alt=""></div>
                            <p class="username">Leo</p>
                    </div>
                    <div class="card">
                        <div class="profile-pic">
                            <img src="{%static 'img/back2.png'%}" alt=""></div>
                        <p class="username">Leo</p>
                    </div>
                    <div class="card">
                        <div class="profile-pic">
                            <img src="{%static 'img/back2.png'%}" alt=""></div>
                            <p class="username">Leo</p>
                    </div> <div class="card">
                        <div class="profile-pic">
                            <img src="{%static 'img/back2.png'%}" alt=""></div>
                            <p class="username">Leo</p>
                    </div>
                   
                </div>
                <div class="post">
                    <div class="abt-post" id="abt-post">
                        <div class="user">
                            <div class="profile-pic">
                                <img src="{%static 'img/back2.png'%}" alt="">
                            </div>
                            <div class="post-footer">
                                <p class="username">Apechi</p>
                              
                                <p class="loc">Nigeria</p>
                            </div>
                           
                            
                    
                        </div>
                        <img src="{%static 'img/option.PNG'%}" class="options" alt="">
                    </div>
                    <img src="{%static 'img/back4.png'%}" class="post-image" alt="">
                    <div class="post-content">
                        <div class="reaction-wrapper">
                            <a href=""><img src="{%static 'img/like.png'%}" class="icon" alt=""></a>
                            <a href=""><img src="{%static 'img/comment.png'%}" class="icon" alt=""></a>
                            <a href=""><img src="{%static 'img/send.png'%}" class="icon"  alt=""></a>
                        </div>
                        <p class="likes">1,012 likes</p>
                        <p class="description"><span>username </span> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Pariatur tenetur veritatis placeat, molestiae impedit aut provident eum quo natus molestias?</p>
                        <p class="post-time">2 minutes ago</p>
                    </div>
                    <div class="comment-wrapper">
                        <img src="{%static 'img/smile.png'%}" class="icon" alt="">
                        <input type="text" class="comment-box" placeholder="Add a comment">
                        <button class="comment-btn">post</button>
                    </div>
                </div>
               
        </div>
        </div>
       
    
                
              
            </div>
        </div>
    </section>
        
</body>
</html>

app/templates/index.html
{%load static%}
{% load fontawesome_5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% fontawesome_5_static %} 
    {%block styles%}
    <link rel="stylesheet" href="{%static 'css/style.css'%}" >
    {%endblock%}
</head>
<body>
   
        {% fa5_icon 'github' 'fab' %}
        
</body>
</html>

app/templates/postform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="col-10" align="center">

        <form id="post_form" method="post" action="" enctype="multipart/form-data">
            <input type="hidden" name="csrfmiddlewaretoken" value="BIslOU7SxIFKhSbPZ99DH8DLNT5spoQiWvDlRdcjKrxGDrm2xnGgt9yHMZknmpAr">
        
            
            <p></p><h4>Caption</h4><p></p>
            
             <input type="text" name="caption" maxlength="2200" id="id_caption"> <br>
            
            <div class="pb-4"></div>
            <small> To submit a post, a photo must be attached to first image box! </small>
        
            <input type="hidden" name="form-TOTAL_FORMS" value="4" id="id_form-TOTAL_FORMS"><input type="hidden" name="form-INITIAL_FORMS" value="0" id="id_form-INITIAL_FORMS"><input type="hidden" name="form-MIN_NUM_FORMS" value="1" id="id_form-MIN_NUM_FORMS"><input type="hidden" name="form-MAX_NUM_FORMS" value="1000" id="id_form-MAX_NUM_FORMS">
            
                
        
        <div id="div_id_form-0-modelimage" class="form-group"> <label for="id_form-0-modelimage" class="col-form-label  requiredField">
                        Image<span class="asteriskField">*</span> </label> <div class=""> <input type="file" name="form-0-modelimage" accept="image/*" class="clearablefileinput" id="id_form-0-modelimage"> </div> </div> <input type="hidden" name="form-0-id" id="id_form-0-id">
        
            
                
        
        <div id="div_id_form-1-modelimage" class="form-group"> <label for="id_form-1-modelimage" class="col-form-label  requiredField">
                        Image<span class="asteriskField">*</span> </label> <div class=""> <input type="file" name="form-1-modelimage" accept="image/*" class="clearablefileinput" id="id_form-1-modelimage"> </div> </div> <input type="hidden" name="form-1-id" id="id_form-1-id">
        
            
                
        
        <div id="div_id_form-2-modelimage" class="form-group"> <label for="id_form-2-modelimage" class="col-form-label  requiredField">
                        Image<span class="asteriskField">*</span> </label> <div class=""> <input type="file" name="form-2-modelimage" accept="image/*" class="clearablefileinput" id="id_form-2-modelimage"> </div> </div> <input type="hidden" name="form-2-id" id="id_form-2-id">
        
            
                
        
        <div id="div_id_form-3-modelimage" class="form-group"> <label for="id_form-3-modelimage" class="col-form-label  requiredField">
                        Image<span class="asteriskField">*</span> </label> <div class=""> <input type="file" name="form-3-modelimage" accept="image/*" class="clearablefileinput" id="id_form-3-modelimage"> </div> </div> <input type="hidden" name="form-3-id" id="id_form-3-id">
        
            
        
        <button type="submit" name="submit" class="btn btn-secondary btn-lg post">
        
            Post
        </button>
        </form>
        </div>
</body>
</html>